@API_HostAddress = https://localhost:7054

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

#### Blogs Endpoints

GET {{API_HostAddress}}/api/Blogs/
Accept: application/json

###

GET {{API_HostAddress}}/api/Blogs?limit=1
Accept: application/json

###

GET {{API_HostAddress}}/api/Blogs?tagIds=1&tagIds=2
Accept: application/json

###

GET {{API_HostAddress}}/api/Blogs/1
Accept: application/json

###

GET {{API_HostAddress}}/api/Blogs/alias/first-blog
Accept: application/json

#### Projects Endpoints

GET {{API_HostAddress}}/api/Projects/
Accept: application/json

###

GET {{API_HostAddress}}/api/Projects/1
Accept: application/json

###

GET {{API_HostAddress}}/api/Projects/alias/project-one
Accept: application/json

###